"""Tests for deterministic OpenAI OAuth deployment config generation."""

from __future__ import annotations

import copy
import stat
from pathlib import Path

import pytest
import yaml

from scripts import generate_openai_oauth_config as generator


ROOT = Path(__file__).resolve().parents[1]


def _base_config() -> dict:
    return {
        "model_list": [
            {
                "model_name": "glm-5.2",
                "litellm_params": {
                    "model": "openai/glm-5.2",
                    "api_key": "os.environ/ZAI_API_KEY",
                },
                "model_info": {"id": "glm-primary", "access_groups": ["zai"]},
            }
        ],
        "router_settings": {
            "routing_strategy": "simple-shuffle",
            "optional_pre_call_checks": ["deployment_affinity"],
            "deployment_affinity_ttl_seconds": 86400,
            "timeout": 60,
        },
        "guardrails": [{"guardrail_name": "ru-pii-mask-pre"}],
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }


def _profile_config() -> dict:
    return {
        "schema_version": 1,
        "models": [
            {
                "public_name": "gpt-5.4",
                "provider_model": "chatgpt/gpt-5.4",
            },
            {
                "public_name": "gpt-5.3-codex",
                "provider_model": "chatgpt/gpt-5.3-codex",
            },
        ],
        "profiles": [
            {"id": "subscription-a", "enabled": True},
            {"id": "subscription-disabled", "enabled": False},
            {"id": "subscription-b", "enabled": True},
        ],
    }


def _write_yaml(path: Path, data: dict) -> None:
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def _generate(
    tmp_path: Path, *, base: dict | None = None, profiles: dict | None = None
):
    base_path = tmp_path / "base.yaml"
    profiles_path = tmp_path / "profiles.local.yaml"
    output_path = tmp_path / "generated" / "litellm-config.local.yaml"
    _write_yaml(base_path, base or _base_config())
    _write_yaml(profiles_path, profiles or _profile_config())
    summary = generator.generate_config(
        base_path=base_path,
        profiles_path=profiles_path,
        output_path=output_path,
    )
    return base_path, profiles_path, output_path, summary


def test_generation_preserves_base_config_and_builds_cartesian_product(tmp_path):
    base = _base_config()
    _, _, output_path, summary = _generate(tmp_path, base=base)

    generated = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    assert generated["model_list"][: len(base["model_list"])] == base["model_list"]
    for key, value in base.items():
        if key not in {"model_list", "router_settings"}:
            assert generated[key] == value
    assert generated["router_settings"] == {
        "routing_strategy": "simple-shuffle",
        "optional_pre_call_checks": ["openai_subscription_affinity"],
        "deployment_affinity_ttl_seconds": 86400,
        "timeout": 60,
        "model_group_affinity_config": {
            "glm-5.2": ["deployment_affinity"],
        },
    }

    oauth = generated["model_list"][len(base["model_list"]) :]
    assert summary.base_deployments == 1
    assert summary.oauth_deployments == 4
    assert [
        (item["model_name"], item["model_info"]["openai_oauth_profile"])
        for item in oauth
    ] == [
        ("gpt-5.4", "subscription-a"),
        ("gpt-5.4", "subscription-b"),
        ("gpt-5.3-codex", "subscription-a"),
        ("gpt-5.3-codex", "subscription-b"),
    ]


def test_generated_deployments_use_canonical_auth_paths_and_stable_ids(tmp_path):
    _, _, output_path, _ = _generate(tmp_path)
    generated = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    oauth = generated["model_list"][1:]

    ids = [item["model_info"]["id"] for item in oauth]
    assert len(ids) == len(set(ids)) == 4
    assert all(model_id.startswith("openai-oauth-") for model_id in ids)
    assert {item["litellm_params"]["chatgpt_auth_file"] for item in oauth} == {
        "/run/secrets/openai-oauth/subscription-a/auth.json",
        "/run/secrets/openai-oauth/subscription-b/auth.json",
    }
    assert {item["model_info"]["base_model"] for item in oauth} == {
        "gpt-5.4",
        "gpt-5.3-codex",
    }


def test_generation_is_byte_deterministic_and_does_not_emit_yaml_aliases(tmp_path):
    _, _, output_path, _ = _generate(tmp_path)
    first = output_path.read_bytes()

    generator.generate_config(
        base_path=tmp_path / "base.yaml",
        profiles_path=tmp_path / "profiles.local.yaml",
        output_path=output_path,
    )
    second = output_path.read_bytes()

    assert first == second
    assert b"&id" not in second
    assert b"*id" not in second
    assert second.startswith(b"# Generated by scripts/generate_openai_oauth_config.py")
    assert stat.S_IMODE(output_path.stat().st_mode) == 0o644


def test_actual_project_inputs_generate_six_oauth_deployments(tmp_path):
    output_path = tmp_path / "litellm-config.local.yaml"
    summary = generator.generate_config(
        base_path=ROOT / "litellm-config.yaml",
        profiles_path=ROOT / "config" / "openai-oauth" / "profiles.example.yaml",
        output_path=output_path,
    )

    base = yaml.safe_load((ROOT / "litellm-config.yaml").read_text(encoding="utf-8"))
    generated = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    assert summary.base_deployments == 4
    assert summary.oauth_deployments == 6
    assert generated["model_list"][:4] == base["model_list"]
    assert generated["router_settings"]["optional_pre_call_checks"] == [
        "openai_subscription_affinity"
    ]
    assert generated["router_settings"]["model_group_affinity_config"] == {
        "glm-5.1": ["deployment_affinity"],
        "glm-5.2": ["deployment_affinity"],
    }
    for key, value in base["router_settings"].items():
        if key != "optional_pre_call_checks":
            assert generated["router_settings"][key] == value
    assert generated["guardrails"] == base["guardrails"]
    assert generated["general_settings"] == base["general_settings"]
    assert generated["litellm_settings"] == base["litellm_settings"]

    oauth = generated["model_list"][4:]
    assert {
        (deployment["model_name"], deployment["model_info"]["openai_oauth_profile"])
        for deployment in oauth
    } == {
        (model, profile)
        for model in ("gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna")
        for profile in ("subscription-a", "subscription-b")
    }
    assert all(
        deployment["litellm_params"]["model"]
        == f"chatgpt/{deployment['model_name']}"
        for deployment in oauth
    )


def test_existing_group_affinity_and_optional_checks_are_preserved(tmp_path):
    base = _base_config()
    base["model_list"].append(
        {
            "model_name": "glm-5.1",
            "litellm_params": {
                "model": "openai/glm-5.1",
                "api_key": "os.environ/ZAI_API_KEY_2",
            },
            "model_info": {"id": "glm-secondary"},
        }
    )
    base["router_settings"]["optional_pre_call_checks"] = [
        "prompt_caching",
        "deployment_affinity",
    ]
    base["router_settings"]["model_group_affinity_config"] = {
        "glm-5.2": ["session_affinity"],
        "gpt-5.4": ["deployment_affinity", "encrypted_content_affinity"],
        "gpt-5.3-codex": ["deployment_affinity"],
    }

    _, _, output_path, _ = _generate(tmp_path, base=base)
    generated = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    router_settings = generated["router_settings"]

    assert router_settings["optional_pre_call_checks"] == [
        "prompt_caching",
        "openai_subscription_affinity",
    ]
    assert router_settings["model_group_affinity_config"] == {
        "glm-5.2": ["session_affinity", "deployment_affinity"],
        "gpt-5.4": ["encrypted_content_affinity"],
        "glm-5.1": ["deployment_affinity"],
    }
    assert "gpt-5.3-codex" not in router_settings["model_group_affinity_config"]


@pytest.mark.parametrize(
    ("router_settings", "message"),
    [
        (None, "must contain router_settings"),
        ({"optional_pre_call_checks": "deployment_affinity"}, "must be a list"),
        ({"model_group_affinity_config": []}, "must be a mapping"),
        (
            {"model_group_affinity_config": {"glm-5.2": "deployment_affinity"}},
            "must map model names",
        ),
    ],
)
def test_invalid_router_affinity_configuration_is_rejected(
    tmp_path, router_settings, message
):
    base = _base_config()
    if router_settings is None:
        del base["router_settings"]
    else:
        base["router_settings"] = router_settings

    with pytest.raises(generator.ConfigGenerationError, match=message):
        _generate(tmp_path, base=base)


def test_generated_file_does_not_contain_profile_secrets_or_local_paths(tmp_path):
    base_path, profiles_path, output_path, _ = _generate(tmp_path)
    rendered = output_path.read_text(encoding="utf-8")

    for forbidden in (
        "access_token",
        "refresh_token",
        "account_id",
        "email",
        str(base_path),
        str(profiles_path),
        "subscription-disabled",
    ):
        assert forbidden not in rendered


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (
            lambda data: data.update(schema_version=2),
            "schema version 1",
        ),
        (
            lambda data: data.update(unexpected=True),
            "contain only schema_version",
        ),
        (
            lambda data: data.update(models=[]),
            "must contain models",
        ),
        (
            lambda data: data["models"][0].update(provider_model="openai/gpt-5.4"),
            "invalid provider_model",
        ),
        (
            lambda data: data["models"].append(copy.deepcopy(data["models"][0])),
            "duplicate public model names",
        ),
        (
            lambda data: data["profiles"][0].update(id="../escape"),
            "invalid id",
        ),
        (
            lambda data: [
                profile.update(enabled=False) for profile in data["profiles"]
            ],
            "enable at least one profile",
        ),
    ],
)
def test_invalid_profile_configuration_is_rejected(tmp_path, mutate, message):
    profiles = _profile_config()
    mutate(profiles)
    base_path = tmp_path / "base.yaml"
    profiles_path = tmp_path / "profiles.yaml"
    output_path = tmp_path / "output.yaml"
    _write_yaml(base_path, _base_config())
    _write_yaml(profiles_path, profiles)

    with pytest.raises(generator.ConfigGenerationError, match=message):
        generator.generate_config(
            base_path=base_path,
            profiles_path=profiles_path,
            output_path=output_path,
        )

    assert not output_path.exists()


def test_duplicate_yaml_mapping_key_is_rejected(tmp_path):
    base_path = tmp_path / "base.yaml"
    profiles_path = tmp_path / "profiles.yaml"
    output_path = tmp_path / "output.yaml"
    _write_yaml(base_path, _base_config())
    profiles_path.write_text(
        """schema_version: 1
models:
  - public_name: gpt-5.4
    public_name: gpt-5.3
    provider_model: chatgpt/gpt-5.4
profiles:
  - id: subscription-a
    enabled: true
""",
        encoding="utf-8",
    )

    with pytest.raises(generator.ConfigGenerationError, match="strict YAML"):
        generator.generate_config(
            base_path=base_path,
            profiles_path=profiles_path,
            output_path=output_path,
        )


def test_oauth_public_name_cannot_join_an_existing_base_model_group(tmp_path):
    base = _base_config()
    base["model_list"][0]["model_name"] = "gpt-5.4"

    with pytest.raises(generator.ConfigGenerationError, match="collide"):
        _generate(tmp_path, base=base)


def test_duplicate_base_deployment_ids_are_rejected(tmp_path):
    base = _base_config()
    duplicate = copy.deepcopy(base["model_list"][0])
    duplicate["model_name"] = "glm-5.1"
    base["model_list"].append(duplicate)

    with pytest.raises(
        generator.ConfigGenerationError, match="duplicate deployment ids"
    ):
        _generate(tmp_path, base=base)


def test_validation_failure_preserves_previous_generated_file(tmp_path):
    base_path, profiles_path, output_path, _ = _generate(tmp_path)
    previous = output_path.read_bytes()
    profiles_path.write_text("schema_version: 2\n", encoding="utf-8")

    with pytest.raises(generator.ConfigGenerationError):
        generator.generate_config(
            base_path=base_path,
            profiles_path=profiles_path,
            output_path=output_path,
        )

    assert output_path.read_bytes() == previous


def test_failed_atomic_write_preserves_previous_file(tmp_path, monkeypatch):
    base_path, profiles_path, output_path, _ = _generate(tmp_path)
    previous = output_path.read_bytes()

    def fail_replace(source_path, destination_path):
        raise OSError("synthetic replace failure")

    monkeypatch.setattr(generator.os, "replace", fail_replace)
    with pytest.raises(generator.ConfigGenerationError, match="cannot write"):
        generator.generate_config(
            base_path=base_path,
            profiles_path=profiles_path,
            output_path=output_path,
        )

    assert output_path.read_bytes() == previous
    assert not list(output_path.parent.glob(f".{output_path.name}.*"))


def test_generator_refuses_to_replace_an_input_file(tmp_path):
    base_path = tmp_path / "base.yaml"
    profiles_path = tmp_path / "profiles.yaml"
    _write_yaml(base_path, _base_config())
    _write_yaml(profiles_path, _profile_config())
    original = base_path.read_bytes()

    with pytest.raises(generator.ConfigGenerationError, match="must not replace"):
        generator.generate_config(
            base_path=base_path,
            profiles_path=profiles_path,
            output_path=base_path,
        )

    assert base_path.read_bytes() == original


def test_generated_output_path_is_ignored_and_static_suite_covers_generator():
    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")

    assert "config/generated/litellm-config.local.yaml" in gitignore
    assert "tests/test_generate_openai_oauth_config.py" in makefile
